-- task 1
CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000),
    start_date DATE DEFAULT SYSDATE,
    end_date DATE,
    budget NUMBER(10, 2)
);

-- task 2
INSERT INTO projects (project_name, description, start_date, end_date, budget)
VALUES (
    'New Technologies Survey',
    'A project aimed at reviewing the area of advanced database technologies.',
    TO_DATE('2018-01-01', 'YYYY-MM-DD'),
    NULL,
    1500000
);
INSERT INTO projects (project_name, description, start_date, end_date, budget)
VALUES (
    'Advanced Data Analysis',
    'Analyzing data obtained from various organizations.',
    TO_DATE('2017-09-20', 'YYYY-MM-DD'),
    TO_DATE('2018-10-01', 'YYYY-MM-DD'),
    2750000
);

SELECT * FROM projects;

-- task 3
INSERT INTO projects (project_id, project_name, description, start_date, end_date, budget)
VALUES (
    55,
    'Creating backbone network',
    'Expanding the organization''s network infrastructure.',
    TO_DATE('2019-06-01', 'YYYY-MM-DD'),
    TO_DATE('2020-05-31', 'YYYY-MM-DD'),
    5000000
);

-- task 4
SELECT
    ROWNUM project_id,
    project_name
FROM projects;

-- task 5
UPDATE projects
SET project_id = 100
WHERE project_name = 'Creating backbone network';

-- task 6
CREATE TABLE projects_copy
AS SELECT * FROM projects;

-- task 7
INSERT INTO projects_copy (project_id, project_name, description, start_date, end_date, budget)
VALUES (
    100,
    'Creating mobile network',
    'Expanding the organization''s network infrastructure – part 2.',
    TO_DATE('2020-06-01', 'YYYY-MM-DD'),
    TO_DATE('2021-05-31', 'YYYY-MM-DD'),
    4000000
);

-- task 8
DELETE FROM projects_copy
WHERE project_name = 'Creating backbone network';

-- task 9
ALTER TABLE projects
ADD (number_of_emp NUMBER(3));

ALTER TABLE projects
MODIFY (description VARCHAR2(1500));

-- task 10
SELECT MAX(LENGTH(project_name)) longest_project_name
FROM projects;

ALTER TABLE projects
MODIFY project_name VARCHAR2(25);

-- task 11
ALTER TABLE projects
RENAME COLUMN budget TO project_budget;

-- task 12
DROP TABLE projects_copy;
